-- Test Drive Appointments Table
CREATE TABLE IF NOT EXISTS public.test_drive_appointments (
  appointment_id  INT GENERATED BY DEFAULT AS IDENTITY,
  account_id      INTEGER REFERENCES public.account(account_id) ON DELETE SET NULL,
  inv_id          INTEGER REFERENCES public.inventory(inv_id) ON DELETE SET NULL,
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  contact_phone   CHARACTER VARYING(20) NOT NULL,
  notes           TEXT,
  status          CHARACTER VARYING(20) NOT NULL DEFAULT 'pending',
  cancellation_reason CHARACTER VARYING(255),
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW(),
  CONSTRAINT appointment_pkey PRIMARY KEY (appointment_id)
);

-- CREATE Unique Column for confirmed appointments
CREATE UNIQUE INDEX IF NOT EXISTS unique_confirmed_slot
  ON public.test_drive_appointments (inv_id, appointment_date, appointment_time)
  WHERE status = 'confirmed';

  -- Appointment Audit Log
  CREATE TABLE IF NOT EXISTS public.appointment_audit_log (
  log_id              INT GENERATED BY DEFAULT AS IDENTITY,
  appointment_id      INTEGER REFERENCES public.test_drive_appointments(appointment_id) ON DELETE SET NULL,
  account_id          INTEGER REFERENCES public.account(account_id) ON DELETE SET NULL,
  account_firstname   CHARACTER VARYING(25),
  account_lastname    CHARACTER VARYING(25),
  account_type        CHARACTER VARYING(20),
  action_type         CHARACTER VARYING(50) NOT NULL,
  previous_status     CHARACTER VARYING(20),
  new_status          CHARACTER VARYING(20),
  vehicle_label       CHARACTER VARYING(255),
  client_name         CHARACTER VARYING(100),
  log_timestamp       TIMESTAMP DEFAULT NOW(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (log_id)
);